matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
      sudo: required

sudo: required

language: python

install:
  - "pip install ansible-core==2.11.3 ansible-lint==3.4.7"
script:
  - cd tests
  - echo "Checking Ansible syntax"
  - ansible-playbook --inventory=localhost, --connection=local test.yml --syntax-check
  - echo "Running Ansible-Lint"
  - ansible-lint test.yml
  - echo "Running the test.yml playbook"
  - ansible-playbook --inventory=localhost, --connection=local test.yml -vvv
