---
- name: ensure basic networking tools are installed
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
  - vlan

- include: all_interfaces.yml
  when: network_interfaces

- name: configurations
  template:
    src: device.j2
    dest: "{{ network_interface_path }}/device-{{ item.0 }}"
  with_items:
  - "{{network_interfaces | default([]) | groupby('device') }}"
  register: network_configuration_result
  notify:
  - network restart interface service
  - network restart interface command

- include: manage_devices.yml
  when: network_manage_devices
