- name: list existing files
  become: "{{ become }}"
  command: "find {{ network_interface_path }} -type f"
  changed_when: no
  register: network_existing_files

# depending on change the result stores dest or path
# check mode doesn't store any of those so use module args
- name: configured files
  become: "{{ become }}"
  set_fact:
    network_configured_files: >-
      [{% for item in network_configuration_result.results | default([]) -%}
        u"{{ item.dest | default(item.path) | default(item.invocation.module_args.dest) }}"
        {{ '' if loop.last else ',' }}
      {%- endfor %}]

- name: remove configurations
  become: "{{ become }}"
  file:
    dest: "{{ item }}"
    state: absent
  when: item not in network_configured_files
  with_items: "{{network_existing_files.stdout_lines | default([])}}"
